# Min-Max Scaling (Normalization)

## Introduction

Min-Max Scaling, also known as **Normalization**, is a feature scaling technique that transforms numerical features into a fixed range, usually between **0 and 1**.

This method rescales the data so that the minimum value becomes 0 and the maximum value becomes 1. It preserves the relationships between original data values while adjusting the scale.

---

## Why Min-Max Scaling is Important

- Ensures all features are within the same range  
- Prevents large-value features from dominating the model  
- Improves performance of distance-based algorithms  
- Helps gradient-based optimization converge faster  

---

## Mathematical Formula

Min-Max Scaling transforms a value \(X\) using the formula:

\[
X_{scaled} = \frac{X - X_{min}}{X_{max} - X_{min}}
\]

Where:

- \(X\) = original value  
- \(X_{min}\) = minimum value of the feature  
- \(X_{max}\) = maximum value of the feature  

After transformation:

- Minimum value → 0  
- Maximum value → 1  

---

## Example Using Scikit-Learn

```python
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X)

### Import requirements

In [20]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

### Load Datset

In [7]:
df=pd.read_csv("Titanic.csv")

In [8]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [11]:
df=df[['Survived','Pclass','Parch']]
df.head()

   Survived  Pclass  Parch
0         0       3      0
1         1       1      0
2         1       3      0
3         1       1      0
4         0       3      0

In [12]:
df.isnull().sum()

Survived    0
Pclass      0
Parch       0
dtype: int64

### Train test split

In [15]:
X=df.drop('Survived',axis=1)
y=df['Survived']

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

In [29]:
# print Shape
print("shape of X_train:",X_train.shape)
print("shape of X_test:",X_test.shape)
print("shape of y_train:",y_train.shape)
print("shape of y_test:",y_test.shape)

shape of X_train: (712, 2)
shape of X_test: (179, 2)
shape of y_train: (712,)
shape of y_test: (179,)

### Apply min-max scaler

In [33]:
mx=MinMaxScaler()

In [36]:
mx.fit(X_train)

MinMaxScaler()

In [38]:
X_train_sc=mx.transform(X_train)
X_test_sc=mx.transform(X_test)

In [39]:
X_train_sc

array([[0.        , 0.        ],
       [0.5       , 0.        ],
       [1.        , 0.        ],
       ...,
       [1.        , 0.        ],
       [0.        , 0.33333333],
       [0.        , 0.16666667]])

In [40]:
X_test_sc

array([[1.        , 0.16666667],
       [0.5       , 0.        ],
       [1.        , 0.        ],
       [0.5       , 0.16666667],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.33333333],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.16666667],
       [1.        , 0.        ],
       [0.5       , 0.        ],
       [0.        , 0.16666667],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [0.5       , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.33333333],
       [0.        , 0.        ],
       [0.5       , 0.        ],
       [1.        , 0.33333333],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [0.5       , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.16666667],
       [1.        , 0.5       ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.33333333],
       [1.        , 0.16666667],
       [0.        , 0.16666667],
       [1.        , 0.66666667],
       [0.        , 0.33333333],
       [1.        , 0.        ],
       [0.        , 0.33333333],
       [0.5       , 0.        ],
       [0.        , 0.16666667],
       [0.5       , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.5       , 0.16666667],
       [0.5       , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [0.5       , 0.        ],
       [0.5       , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.16666667],
       [0.        , 0.        ],
       [0.5       , 0.16666667],
       [0.        , 0.33333333],
       [0.        , 0.        ],
       [0.        , 0.16666667],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.33333333],
       [0.5       , 0.        ],
       [1.        , 0.33333333],
       [1.        , 0.16666667],
       [0.5       , 0.        ],
       [0.        , 0.16666667],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.33333333],
       [1.        , 0.33333333],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [0.5       , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.5       , 0.16666667],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [0.5       , 0.        ],
       [0.5       , 0.16666667],
       [1.        , 0.5       ],
       [0.5       , 0.16666667],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.5       , 0.33333333],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.16666667],
       [0.5       , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.5       , 0.        ],
       [0.5       , 0.        ],
       [0.5       , 0.        ],
       [1.        , 0.83333333],
       [0.5       , 0.16666667],
       [0.5       , 0.        ],
       [0.5       , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.5       , 0.        ],
       [1.        , 0.16666667],
       [1.        , 0.        ],
       [0.        , 0.        ],
       [0.5       , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.16666667],
       [0.5       , 0.        ],
       [0.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 0.16666667],
       [0.5       , 0.33333333],
       [0.        , 0.        ],
       [1.        , 0.16666667],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.83333333],
       [0.5       , 0.        ],
       [1.        , 0.16666667]])